image: ruby:2.6

variables:
  LC_ALL: C.UTF-8

cache:
  paths:
  - vendor/

pages:
  stage: deploy
  script:
    - gem install bundler
    - bundle install --path vendor
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
