image: ruby:2.6

variables:
  LC_ALL: C.UTF-8

cache:
  paths:
  - vendor/

pages:
  stage: deploy
  script:
    - apt-get update && apt-get install moreutils -y
    - gem install bundler
    - bundle install --path vendor
    - cd scripts && ./docs.sh && ./docs_nav.sh && git checkout ../_docs/index.md && cd ..
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
